platform :ios, '10.3'

target 'CustomResource' do
  
  pod 'AFNetworking'
  pod 'Bugly'
  pod 'GTSDK'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'pop'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'TPKeyboardAvoiding'
  pod 'TTTAttributedLabel'
  pod 'TZImagePickerController'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'YYKit'

end
